[package]
name = "cargo-feature"
description = "Allows conveniently modify features of crate"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.12"
toml_edit = "0.1.5"
