name: CI

on:
  push:
    branches:
      - 'develop'
      - 'releases/*'
  pull_request:
    branches:
      - 'develop'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build

  format:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Check Rustfmt
        run: cargo fmt -- --check
